# Generated by Django 3.0.6 on 2020-06-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_color', '0002_auto_20200502_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='awcolor',
            name='Slug',
            field=models.CharField(blank=True, default=True, max_length=120),
        ),
    ]
