# Generated by Django 3.0.6 on 2020-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_color', '0003_awcolor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awcolor',
            name='Slug',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
