# Generated by Django 3.0.6 on 2020-11-05 11:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wine_palate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwWinePalateCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('Category_image', models.ImageField(blank=True, null=True, upload_to=wine_palate.models.user_directory_path_for_product)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Aw Wine Palate Categories',
            },
        ),
        migrations.CreateModel(
            name='AwWinePalateFlavors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=120, null=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category_AwWinePalateCategories', to='wine_palate.AwWinePalateCategories')),
            ],
            options={
                'verbose_name_plural': 'Aw Wine Palate Flavors',
            },
        ),
    ]
