# Generated by Django 3.0.6 on 2020-11-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_palate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awwinepalatecategories',
            name='Category_Color',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
