# Generated by Django 3.0.6 on 2020-11-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_palate', '0002_awwinepalatecategories_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='awwinepalatecategories',
            name='Category_Type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
