# Generated by Django 3.0.6 on 2020-11-21 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wine_palate', '0003_awwinepalatecategories_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwUserPalateWine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('Type', models.CharField(blank=True, max_length=120, null=True)),
                ('CategoryNameAndType', models.CharField(blank=True, max_length=120, null=True)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Palates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aw User Palate Wine',
            },
        ),
    ]
