# Generated by Django 3.0.6 on 2020-11-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_palate', '0004_awuserpalatewine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awuserpalatewine',
            name='Category_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
