# Generated by Django 3.0.6 on 2020-12-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_palate', '0005_auto_20201121_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='awwinepalatecategories',
            name='Category_Id',
            field=models.IntegerField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
