# Generated by Django 3.0.6 on 2020-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_appellation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awappellation',
            name='Slug',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
