# Generated by Django 3.0.6 on 2020-06-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_appellation', '0002_awappellation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awappellation',
            name='Slug',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
