# Generated by Django 3.0.6 on 2020-12-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_country', '0004_auto_20200921_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='awcountry',
            name='Short_Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
