# Generated by Django 3.0.6 on 2020-12-21 09:44

import admin_manage_country.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_country', '0007_auto_20201221_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awcountry',
            name='Country_Image',
            field=models.ImageField(blank=True, default='http://3.133.12.113/media/Toscana/Region/banner/2020/11/9/tuscany-wine.jpg', null=True, upload_to=admin_manage_country.models.user_directory_path),
        ),
    ]
