# Generated by Django 3.0.6 on 2020-12-21 10:20

import admin_manage_country.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_country', '0010_auto_20201221_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awcountry',
            name='Country_Image',
            field=models.ImageField(blank=True, default='default/default_country_image.jpg', null=True, upload_to=admin_manage_country.models.user_directory_path),
        ),
    ]
