# Generated by Django 3.0.6 on 2020-06-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_Vintages', '0002_auto_20200501_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='awvintages',
            name='Slug',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
