# Generated by Django 3.0.6 on 2020-06-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_producer', '0002_awproducers'),
    ]

    operations = [
        migrations.AddField(
            model_name='awproducers',
            name='Slug',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
