# Generated by Django 3.0.6 on 2020-12-21 11:52

import admin_manage_region.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_region', '0004_auto_20200921_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awregion',
            name='Region_Image',
            field=models.ImageField(blank=True, default='default/default_region_image.png', null=True, upload_to=admin_manage_region.models.user_directory_path),
        ),
    ]
