# Generated by Django 3.0.6 on 2020-06-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_varietals', '0002_awvarietals_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awvarietals',
            options={'verbose_name_plural': 'AW Varietals'},
        ),
    ]
