# Generated by Django 3.0.4 on 2020-05-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_categoryes', '0002_auto_20200429_1928'),
        ('admin_manage_classification', '0001_initial'),
        ('admin_manage_color', '0002_auto_20200502_1431'),
        ('admin_manage_appellation', '0001_initial'),
        ('admin_manage_varietals', '0001_initial'),
        ('admin_manage_grape', '0001_initial'),
        ('admin_manage_size', '0001_initial'),
        ('admin_manage_Vintages', '0002_auto_20200501_1150'),
        ('admin_manage_products', '0004_auto_20200502_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awproductprice',
            old_name='Descount_Cose',
            new_name='Descount_Cost',
        ),
        migrations.AlterField(
            model_name='awproducts',
            name='Appellation',
            field=models.ManyToManyField(related_name='AwProducts_Appellation', to='admin_manage_appellation.AwAppellation'),
        ),
        migrations.AlterField(
            model_name='awproducts',
            name='Bottel_Size',
            field=models.ManyToManyField(related_name='AwProducts_Bottel_Size', to='admin_manage_size.AwSize'),
        ),
        migrations.AlterField(
            model_name='awproducts',
            name='Category',
            field=models.ManyToManyField(related_name='AwProducts_Category', to='admin_manage_categoryes.AwCategory'),
        ),
        migrations.AlterField(
            model_name='awproducts',
            name='Classification',
            field=models.ManyToManyField(related_name='AwProducts_Classification', to='admin_manage_classification.AwClassification'),
        ),
        migrations.AlterField(
            model_name='awproducts',
            name='Color',
            field=models.ManyToManyField(related_name='AwProducts_Color', to='admin_manage_color.AwColor'),
        ),
        migrations.AlterField(
            model_name='awproducts',
            name='Grape',
            field=models.ManyToManyField(related_name='AwProducts_Grape', to='admin_manage_grape.AwGrape'),
        ),
        migrations.AlterField(
            model_name='awproducts',
            name='Varietals',
            field=models.ManyToManyField(related_name='AwProducts_Varietals', to='admin_manage_varietals.AwVarietals'),
        ),
        migrations.AlterField(
            model_name='awproducts',
            name='Vintage',
            field=models.ManyToManyField(related_name='AwProducts_Vintage', to='admin_manage_Vintages.AwVintages'),
        ),
    ]
