# Generated by Django 3.0.6 on 2020-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0005_auto_20200504_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='awproductprice',
            name='Bond_Descount_Cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='awproductprice',
            name='Bond_Stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='awproductprice',
            name='Duty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='awproductprice',
            name='GST',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='awproductprice',
            name='Retail_Stock',
            field=models.IntegerField(default=0),
        ),
    ]
