# Generated by Django 3.0.6 on 2020-05-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0006_auto_20200528_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awproductprice',
            name='Bond_Descount_Cost',
            field=models.FloatField(default=0),
        ),
    ]
