# Generated by Django 3.0.6 on 2020-06-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0007_auto_20200528_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awproductprice',
            name='Duty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='awproductprice',
            name='GST',
            field=models.FloatField(default=0),
        ),
    ]
