# Generated by Django 3.0.6 on 2020-10-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20201017_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aworders',
            name='shipping_charge',
            field=models.FloatField(default=0),
        ),
    ]
