# Generated by Django 3.0.6 on 2020-10-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20201019_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aworders',
            name='Amount',
            field=models.FloatField(default=0),
        ),
    ]
