# Generated by Django 3.0.6 on 2020-10-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20201027_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aworders',
            name='order_amount',
            field=models.FloatField(default=0),
        ),
    ]
