# Generated by Django 3.0.6 on 2020-10-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20201027_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='aworederitem',
            name='Order_Quentity',
            field=models.IntegerField(default=0),
        ),
    ]
