# Generated by Django 3.0.4 on 2020-05-02 10:10

import admin_manage_products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_manage_products', '0002_awproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_Type', models.CharField(blank=True, max_length=120, null=True)),
                ('Image', models.ImageField(upload_to=admin_manage_products.models.user_directory_path)),
                ('Status', models.BooleanField(default=True)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProductImage_Created_by', to=settings.AUTH_USER_MODEL)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProductImage_Product', to='admin_manage_products.AwProducts')),
                ('Updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwProductImage_Updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aw Product Image',
            },
        ),
    ]
