# Generated by Django 3.0.6 on 2020-11-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0007_auto_20200911_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='awproducts',
            name='LWine',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
