# Generated by Django 3.0.6 on 2020-11-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0010_awproductreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='awproductreviews',
            name='drinkTo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
