# Generated by Django 3.0.6 on 2020-12-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0012_awproductprice_aroma_cose'),
    ]

    operations = [
        migrations.AddField(
            model_name='awproducts',
            name='AlcoholPercentage',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
