# Generated by Django 3.0.6 on 2020-12-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0013_awproducts_alcoholpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awproducts',
            name='AlcoholPercentage',
            field=models.FloatField(default=0),
        ),
    ]
