# Generated by Django 3.0.6 on 2020-12-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0014_auto_20201216_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awproducts',
            name='AlcoholPercentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
