# Generated by Django 3.0.6 on 2020-12-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_palate', '0005_auto_20201121_2231'),
        ('admin_manage_products', '0015_auto_20201216_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='awproducts',
            name='Flaver',
            field=models.ManyToManyField(related_name='AwWinePalateFlavors_Flaver', to='wine_palate.AwWinePalateFlavors'),
        ),
    ]
