# Generated by Django 3.0.6 on 2020-12-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0016_awproducts_flaver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awproducts',
            old_name='Flaver',
            new_name='Flavours',
        ),
    ]
