# Generated by Django 3.0.6 on 2020-12-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_palate', '0005_auto_20201121_2231'),
        ('admin_manage_products', '0017_auto_20201219_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awproducts',
            name='Flavours',
            field=models.ManyToManyField(blank=True, null=True, related_name='AwWinePalateFlavors_Flaver', to='wine_palate.AwWinePalateFlavors'),
        ),
    ]
