# Generated by Django 3.0.6 on 2020-12-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_varietals', '0001_initial'),
        ('admin_manage_products', '0019_auto_20201224_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='awproducts',
            name='Analytical_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='awproducts',
            name='Varietals',
            field=models.ManyToManyField(blank=True, null=True, related_name='AwProducts_Varietals', to='admin_manage_varietals.AwVarietals'),
        ),
    ]
