# Generated by Django 3.0.6 on 2020-12-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0021_awproducts_foodpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='awproducts',
            name='is_copy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='awproducts',
            name='parent_product_code',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
