# Generated by Django 3.0.6 on 2020-12-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_products', '0022_auto_20201230_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awproducts',
            name='parent_product_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
