# Generated by Django 3.0.6 on 2021-01-02 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_size', '0001_initial'),
        ('admin_manage_products', '0024_auto_20210101_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='awproductprice',
            name='Bottel_Size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwSize_Bottel_AwProductPrice', to='admin_manage_size.AwSize'),
        ),
    ]
