# Generated by Django 3.0.4 on 2020-05-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_color', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awcolor',
            options={'verbose_name_plural': 'AW Color'},
        ),
    ]
