# Generated by Django 3.0.6 on 2020-12-21 10:43

import admin_manage_producer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manage_producer', '0004_auto_20200921_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awproducers',
            name='Producer_Image',
            field=models.ImageField(blank=True, default='default/default_producer_image.png', null=True, upload_to=admin_manage_producer.models.user_directory_path),
        ),
    ]
